export const TOGGLE_SEARCH_BOX = 'TOGGLE_SEARCH_BOX';
export const TOGGLE_MENU = 'TOGGLE_MENU';

export const FREE_ARTICLE = 'FREE_ARTICLE';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLE_FAILED = 'FETCH_ARTICLE_FAILED';
